# 11th July 2026

In [6]:
%pip install apyori

Requirement already satisfied: apyori in c:\Users\barat\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
from apyori import apriori

df = pd.read_csv(r"C:\Users\barat\Downloads\Market_Basket_Optimisation.csv",header=None)
all_transactions = []
for i in df.index:
    row = df.loc[i].values
    transaction = []
    for item in row:
        if str(item)!="nan":
            transaction.append(item)
    all_transactions.append(transaction)

result = pd.DataFrame(list(apriori(all_transactions,min_support = 0.003,min_confidence=0.03,min_lift=0.2)))
support = result['support']
first_value = []
second_value=[]
third_value = []
fourth_value = []
for i in result.index:
    row = result['ordered_statistics'].loc[i][0]
    first_value.append(list(row[0]))
    second_value.append(list(row[1]))
    third_value.append(row[2])
    fourth_value.append(row[3])
lhs = pd.DataFrame(first_value) 
rhs = pd.DataFrame(second_value)
confidence = pd.DataFrame(third_value,columns=['Confidence'])
lift = pd.DataFrame(fourth_value,columns=['Lift'])
output = pd.concat([lhs,rhs,support,confidence,lift],axis=1)
output.sort_values(by=['Lift'],ascending=False)

,0,1,0,1,2,support,Confidence,Lift
1302,olive oil,NaN,mineral water,whole wheat pasta,NaN,0.003866,0.058704,6.115863
509,fromage blanc,NaN,honey,NaN,NaN,0.003333,0.245098,5.164271
1257,ground beef,NaN,spaghetti,tomato sauce,NaN,0.003066,0.031208,4.980600
236,chicken,NaN,light cream,NaN,NaN,0.004533,0.075556,4.843951
424,escalope,NaN,pasta,NaN,NaN,0.005866,0.073950,4.700812
...,...,...,...,...,...,...,...,...
315,cookies,NaN,spaghetti,NaN,NaN,0.007999,0.099502,0.571492
309,cookies,NaN,ground beef,NaN,NaN,0.004399,0.054726,0.556991
147,butter,NaN,mineral water,NaN,NaN,0.003066,0.101770,0.426944
311,cookies,NaN,milk,NaN,NaN,0.004399,0.054726,0.422328
312,cookies,NaN,mineral water,NaN,NaN,0.007466,0.092869,0.389603

In [8]:
import pandas as pd
df = pd.read_csv(r"C:\Users\barat\Downloads\rawDataset.csv",header=None,on_bad_lines='skip')
df.drop([0,1],axis=1,inplace=True)
all_transactions = []
for i in df.index:
    row = df.loc[i].values
    transaction = []
    for item in row:
        if str(item)!="nan":
            transaction.append(item)
    all_transactions.append(transaction)

result = pd.DataFrame(list(apriori(all_transactions,min_support = 0.003,min_confidence=0.03,min_lift=0.2)))
support = result['support']
first_value = []
second_value=[]
third_value = []
fourth_value = []
for i in result.index:
    row = result['ordered_statistics'].loc[i][0]
    first_value.append(list(row[0]))
    second_value.append(list(row[1]))
    third_value.append(row[2])
    fourth_value.append(row[3])
lhs = pd.DataFrame(first_value) 
rhs = pd.DataFrame(second_value)
confidence = pd.DataFrame(third_value,columns=['Confidence'])
lift = pd.DataFrame(fourth_value,columns=['Lift'])
output = pd.concat([lhs,rhs,support,confidence,lift],axis=1)
output.sort_values(by=['Lift'],ascending=False)

,0,0,1,support,Confidence,Lift
0,NaN,,NaN,0.188023,0.188023,1.000000
1,NaN,Bhuna - Chicken,NaN,0.202833,0.202833,1.000000
2,NaN,Chicken Tikka Balti,NaN,0.186735,0.186735,1.000000
3,NaN,Curry,NaN,0.213136,0.213136,1.000000
4,NaN,House white wine 75cl,NaN,0.216355,0.216355,1.000000
5,NaN,Korma - Lamb,NaN,0.184804,0.184804,1.000000
6,NaN,Lamb Biryani,NaN,0.200258,0.200258,1.000000
7,NaN,Plain Rice,NaN,0.203477,0.203477,1.000000
8,NaN,Special Fried Rice,NaN,0.218287,0.218287,1.000000
9,NaN,Vindaloo - Prawn,NaN,0.186091,0.186091,1.000000
40,NaN,House white wine 75cl,Korma - Lamb,0.030908,0.030908,1.000000
31,Chicken Tikka Balti,Plain Rice,NaN,0.028332,0.151724,0.745657
44,House white wine 75cl,Vindaloo - Prawn,NaN,0.028332,0.130952,0.703699
18,,Vindaloo - Prawn,NaN,0.023825,0.126712,0.680914
36,Curry,Lamb Biryani,NaN,0.028976,0.135952,0.678884
33,Chicken Tikka Balti,Vindaloo - Prawn,NaN,0.023181,0.124138,0.667080
50,Lamb Biryani,Special Fried Rice,NaN,0.028976,0.144695,0.662863
12,,Curry,NaN,0.026401,0.140411,0.658786
25,Bhuna - Chicken,Special Fried Rice,NaN,0.028976,0.142857,0.654446
45,Korma - Lamb,Lamb Biryani,NaN,0.023825,0.128920,0.643770
37,Curry,Plain Rice,NaN,0.027044,0.126888,0.623599
14,,Korma - Lamb,NaN,0.021249,0.113014,0.611534
41,House white wine 75cl,Lamb Biryani,NaN,0.026401,0.122024,0.609334
35,Curry,Korma - Lamb,NaN,0.023825,0.111782,0.604872
43,House white wine 75cl,Special Fried Rice,NaN,0.028332,0.130952,0.599909
20,Bhuna - Chicken,Curry,NaN,0.025757,0.126984,0.595790
53,Plain Rice,Vindaloo - Prawn,NaN,0.022537,0.110759,0.595189
24,Bhuna - Chicken,Plain Rice,NaN,0.024469,0.120635,0.592867
54,Special Fried Rice,Vindaloo - Prawn,NaN,0.023825,0.109145,0.586510
10,,Bhuna - Chicken,NaN,0.021893,0.116438,0.574060
21,Bhuna - Chicken,House white wine 75cl,NaN,0.025113,0.123810,0.572251
32,Chicken Tikka Balti,Special Fried Rice,NaN,0.023181,0.124138,0.568691
17,,Special Fried Rice,NaN,0.023181,0.123288,0.564796
49,Lamb Biryani,Plain Rice,NaN,0.022537,0.112540,0.553085
26,Bhuna - Chicken,Vindaloo - Prawn,NaN,0.020605,0.101587,0.545900
38,Curry,Special Fried Rice,NaN,0.025113,0.117825,0.539770
27,Chicken Tikka Balti,Curry,NaN,0.021249,0.113793,0.533899
19,Bhuna - Chicken,Chicken Tikka Balti,NaN,0.019961,0.098413,0.527017
48,Korma - Lamb,Vindaloo - Prawn,NaN,0.018030,0.097561,0.524264
16,,Plain Rice,NaN,0.019961,0.106164,0.521751
34,Curry,House white wine 75cl,NaN,0.023825,0.111782,0.516661
30,Chicken Tikka Balti,Lamb Biryani,NaN,0.019317,0.103448,0.516576
52,Plain Rice,Special Fried Rice,NaN,0.022537,0.110759,0.507403
29,Chicken Tikka Balti,Korma - Lamb,NaN,0.017386,0.093103,0.503797
22,Bhuna - Chicken,Korma - Lamb,NaN,0.018030,0.088889,0.480991
11,,Chicken Tikka Balti,NaN,0.016742,0.089041,0.476830
46,Korma - Lamb,Plain Rice,NaN,0.017386,0.094077,0.462345
15,,Lamb Biryani,NaN,0.017386,0.092466,0.461734
23,Bhuna - Chicken,Lamb Biryani,NaN,0.018030,0.088889,0.443873
28,Chicken Tikka Balti,House white wine 75cl,NaN,0.017386,0.093103,0.430326
13,,House white wine 75cl,NaN,0.017386,0.092466,0.427379
42,House white wine 75cl,Plain Rice,NaN,0.018674,0.086310,0.424173
51,Lamb Biryani,Vindaloo - Prawn,NaN,0.014810,0.073955,0.397412
47,Korma - Lamb,Special Fried Rice,NaN,0.014166,0.076655,0.351166
39,Curry,Vindaloo - Prawn,NaN,0.010947,0.051360,0.275991